### ISSUE TITLE
request>nlu>intents 

### ISSUE THREAD

**Issue by chilikbayevabay** [alexvolchetsky/yandex.alice.sdk#1]
Добавить поддержку intents

**Comment by alexvolchetsky** [comment]
Спасибо за предложение. Постараюсь добавить интенты в ближайшее время

**Comment by alexvolchetsky** [comment]
Добавил поддержку интентов и обновил nuget package
https://www.nuget.org/packages/Yandex.Alice.Sdk/1.0.4

Смотрите инструкции об использовании здесь: 
[Интенты](https://github.com/alexvolchetsky/yandex.alice.sdk/wiki/%D0%98%D0%BD%D1%82%D0%B5%D0%BD%D1%82%D1%8B)
