### ISSUE TITLE
Add typed converters to avoid casting of slot models

### ISSUE THREAD

**Issue by MrDaedra** [alexvolchetsky/yandex.alice.sdk#5]
Currently there is a property
```
[JsonPropertyName("what")]
[JsonConverter(typeof(AliceEntityModelConverter))]
public AliceEntityModel What { get; set; }
```
and the developer should cast it each time in order to use its value:
```
var what = aliceRequest.Request.Nlu.Intents.TurnOn.Slots.What as AliceEntityStringModel;
```
It would be way better if it was possible to use it as follows:
```
[JsonPropertyName("what")]
[JsonConverter(typeof(AliceEntityStringModelConverter))]
public AliceEntityStringModel What { get; set; }
```

**Comment by alexvolchetsky** [comment]
Slots classes are fully controlled by developers. You can use `AliceEntityStringModel` directly in your models:
```
[JsonPropertyName("what")]
public AliceEntityStringModel What { get; set; }
```
Created PR #6 with example. As currently it can be confusing how slot models are using.
@MrDaedra  Can you please check this PR and let me know if this is what you expect?

**Comment by MrDaedra** [comment]
Yes, seems like this issue can be closed
