### ISSUE TITLE
AliceEntityModel.Value is missing

### ISSUE THREAD

**Issue by Fluttercom** [alexvolchetsky/yandex.alice.sdk#9]
Looks like AliceEntityModel.Value for simple utterance is missing
```
{
          "tokens": {
            "start": 3,
            "end": 5
          },
          "type": "YANDEX.FIO",
          "value": {
            "first_name": "лев",
            "last_name": "толстой"
          }
        },
```
https://yandex.ru/dev/dialogs/alice/doc/request-simpleutterance.html

**Comment by Fluttercom** [comment]
Got it, thanks.

**Comment by Fluttercom** [comment]
Still I see one issue in this case:
`"entities": [
        {
          "type": "YANDEX.GEO",
          "tokens": {
            "start": 0,
            "end": 1
          },
          "value": {
            "country": "Бразилия"
          }
        }`
Parser returns AliceEntityGeoValueModel from value, which got no Country property.

**Comment by alexvolchetsky** [comment]
Thank you for finding that! It seems like a bug. 
[AliceEntityGeoValueModel](https://github.com/alexvolchetsky/yandex.alice.sdk/blob/ec1c0aeacfe3ce47c9cc23e47bf407947bc7f5b0/src/Yandex.Alice.Sdk/Models/AliceEntityGeoValueModel.cs) is missing the following fields according to the [documentation](https://yandex.ru/dev/dialogs/alice/doc/naming-entities.html#naming-entities__geo):

- country
- city
- airport

If you are willing and have the time, would you consider submitting a Pull Request to address the bug? :)

**Comment by Fluttercom** [comment]
Also I noticed YANDEX.DATETIME can have absolute and relative forms, which seems is not handled:
```
"type": "YANDEX.DATETIME",
"value": {
  "year": 1982,
  "month": 9,
  "day": 15,
  "hour": 22,
  "minute": 30,
}
```
